.TH "MDASTRC" "5" "April 2015" "" ""
.SH "NAME"
\fBmdastrc\fR \- mdast config files
.SH SYNOPSIS
.P
\fB\|\.mdastrc\fR, \fBpackage\.json\fR
.SH DESCRIPTION
.P
\fBmdast\fR gets its configuration from the command line and \fBmdastrc\fR files\.
.P
For a list of available configuration options, see \fBmdast\fR(1) or <https://github\.com/wooorm/mdast/blob/master/doc/Options\.md>\.
.SH FILES
.P
All \fBmdastrc\fR(5) configuration files are in JSON\.
.P
Automatically detected files named \fBpackage\.json\fR use the \fBmdastConfig\fR field, whereas other files are used as a whole\.
.SH CASCADE
.P
Precedence is as follows:
.RS 0
.IP \(bu 2
Plug\-ins and settings passed to \fBmdast\fR(1);
.IP \(bu 2
File passed to \fBmdast\fR(1);
.IP \(bu 2
Files named \fB\|\.mdastrc\fR and \fBmdastConfig\fR fields in \fBpackage\.json\fR in the directory of the processed file, and in ancestral directories;
.IP \(bu 2
If no \fB\|\.mdastrc\fR and \fBpackage\.json\fR were detected in the directory of the file or its ancestral directories, a per\-user config file (\fB~/\.mdastrc\fR) is used;

.RE
.P
If both \fB\|\.mdastrc\fR and \fBpackage\.json\fR exist in a directory, the file named \fB\|\.mdastrc\fR takes precedence in the cascade over \fBpackage\.json\fR\|\.
.P
For example, for the following project:
.P
.RS 2
.nf
project
|\-\- docs
|   |\-\- \.mdastrc
|   |\-\- Doc\.md
|
|\-\- \.mdastrc
|\-\- package\.json
|\-\- Readme\.md
.fi
.RE
.P
Where \fBdoc/\.mdastrc\fR looks as follows:
.P
.RS 2
.nf
{
    "settings": {
        "bullet": "+"
    }
}
.fi
.RE
.P
And \fBpackage\.json\fR contains:
.P
.RS 2
.nf
{
    "mdastConfig": {
        "settings": {
            "bullet": "*"
        }
    }
}
.fi
.RE
.P
And \fB\|\.mdastrc\fR contains:
.P
.RS 2
.nf
{
    "settings": {
        "bullet": "\-"
    }
}
.fi
.RE
.P
Then, when stringifying \fBdocs/Doc\.md\fR, \fBmdast\fR(1) would use \fBbullet: "+"\fR because \fBdoc/\.mdastrc\fR takes precedence over \fB\|\.mdastrc\fR and \fBpackage\.json\fR\|\.
.P
When stringifying \fBReadme\.md\fR, \fBmdast\fR(1) would use \fBbullet: "\-"\fR, because \fB\|\.mdastrc\fR takes precedence over \fBpackage\.json\fR\|\.
.SH BUGS
.P
<https://github\.com/wooorm/mdast/issues>
.SH SEE ALSO
.P
\fBmdast\fR(1), \fBmdastignore\fR(5), \fBmdastconfig\fR(7)\.
.SH AUTHOR
.P
Written by Titus Wormer <mailto:tituswormer@gmail\.com>

