.TH "MDAST" "1" "March 2015" "" ""
.SH "NAME"
\fBmdast\fR \- Markdown parser and stringifier
.SH SYNOPSIS
.P
\fBmdast\fR [\fB\-a\fR, \fB\-\-ast\fR] [\fB\-q\fR, \fB\-\-quiet\fR] [\fB\-o\fR, \fB\-\-output\fR [\fIpath\fR]] [\fB\-s\fR, \fB\-\-setting\fR \fIsettings\fR] [\fB\-u\fR, \fB\-\-use\fR \fIplugins\fR] [\fB\-c\fR, \fB\-\-config\-path\fR \fIpath\fR] [\fB\-i\fR, \fB\-\-ignore\-path\fR \fIpath\fR] [\fB\-e\fR, \fB\-\-ext\fR [\fIextensions\fR]] [\fB\-\-no\-rc\fR] [\fB\-\-no\-ignore\fR] \fIfile|dir\fR \fI\|\.\.\.\fR
.P
\fBmdast\fR \fI\-\-settings\fR
.SH DESCRIPTION
.P
\fBmdast\fR is speedy Markdown parser (and stringifier) for multipurpose analysis in JavaScript\.  Node\.js and browser\.  Lots of tests\.  100% coverage\.
.P
Logs verbose debugging information when \fB$DEBUG\fR is set to \fB"mdast"\fR\|\.
.P
Options are as follows:
.RS 0
.IP \(bu 2
\fB\-h\fR, \fB\-\-help\fR: Output usage information;
.IP \(bu 2
\fB\-V\fR, \fB\-\-version\fR: Output version number;
.IP \(bu 2
\fB\-o\fR, \fB\-\-output\fR \fIpath\fR: Specify output location\.  When \fIpath\fR is omitted, input files are overwritten;
.IP \(bu 2
\fB\-c\fR, \fB\-\-config\-path\fR \fIpath\fR: Specify configuration location;
.IP \(bu 2
\fB\-i\fR, \fB\-\-ignore\-path\fR \fIpath\fR: Specify ignore location;
.IP \(bu 2
\fB\-s\fR, \fB\-\-setting\fR \fIsettings\fR: Specify settings;
.IP \(bu 2
\fB\-u\fR, \fB\-\-use\fR \fIplugins\fR: Use transform plugin(s);
.IP \(bu 2
\fB\-e\fR, \fB\-\-ext\fR \fIextensions\fR: Specify file extensions to look for;
.IP \(bu 2
\fB\-a\fR, \fB\-\-ast\fR: Output AST information;
.IP \(bu 2
\fB\-q\fR, \fB\-\-quiet\fR: Output less messages;
.IP \(bu 2
\fB\-\-no\-rc\fR: Disable configuration from \fI\|\.mdastrc\fR;
.IP \(bu 2
\fB\-\-no\-ignore\fR: Disable ignoring from \fI\|\.mdastignore\fR;
.IP \(bu 2
\fB\-\-settings\fR: Output available settings\.

.RE
.P
A \fB\-\-\fR argument tells the cli parser to stop reading flags\.
.SH DIAGNOSTICS
.P
\fBmdast\fR exits 0 on success, and 1 otherwise\.
.SH BUGS
.P
 \fIhttps://github\.com/wooorm/mdast/issues\fR
.SH SEE ALSO
.P
\fBmdastrc\fR(5), \fBmdastignore\fR(5)\.
.SH AUTHOR
.P
Written by Titus Wormer  \fItituswormer@gmail\.com\fR

